# Please make sure to update the license_key information with the license key for your New Relic
# account.
#
#
newrelic:
  #
  # Update with your New Relic account license key:
  #
  license_key: 'YOUR_LICENSE_KEY_HERE'
  #
  # Set to '1' for verbose output, remove for normal output.
  # All output goes to stdout/stderr.
  #
  # verbose: 1
#
# Agent Configuration:
#
agents:
  # this is where configuration for agents belongs
  openldap_agent:
    -
      name: "CHANGE_ME"
      host: "localhost"
      port: "389"
      dn: "cn=admin,dc=example,dc=com"
      password: "password"
      # For monitoring replication status
      server_id: 001
      replication_base: "dc=example,dc=com"
      replication_providers:
        - provider1.example.com
        - provider2.example.com
